services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DD_TRACE_ENABLED=true
      - DD_TRACE_DEBUG=true
      - DD_TRACE_STARTUP_LOGS=true
      - DD_SERVICE=flask-psycopg-bug
      - DD_ENV=dev
      - DD_VERSION=1.0.0
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_URL=http://datadog-agent:8126
    depends_on:
      datadog-agent:
        condition: service_healthy
    networks:
      - flask-patch-all-network

  datadog-agent:
    image: datadog/agent:latest
    ports:
      - "127.0.0.1:8126:8126/tcp"
    env_file:
      - ../../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    networks:
      - flask-patch-all-network

networks:
  flask-patch-all-network:
    driver: bridge
